export const GET_ALL_BANNER_LIST_REQUEST = 'GET_ALL_BANNER_LIST_REQUEST';
export const GET_ALL_BANNER_LIST_LOADING = 'GET_ALL_BANNER_LIST_LOADING';
export const GET_ALL_BANNER_LIST_SUCCESS = 'GET_ALL_BANNER_LIST_SUCCESS';
export const GET_ALL_BANNER_LIST_ERROR = 'GET_ALL_BANNER_LIST_ERROR';
export const GET_ALL_BANNER_LIST_RESET = 'GET_ALL_BANNER_LIST_RESET';

